{
 "title": "1C APDEX Example",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Приложение",
    "query": {
     "query": "label_values(onec_apdex_total_value,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "APDEX. Профиль \"Полный\"",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keyoperation) (onec_apdex_total_value{profile=\"Полный\", exported_instance=\"$instance\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "APDEX по профилям",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "min by(profile) (onec_apdex_total_value{keyoperation=\"Все\", exported_instance=\"$instance\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения операции",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "onec_apdex_average_duration_of_the_operation{profile=\"Полный\", exported_instance=\"$instance\"}",
     "legendFormat": "{{keyoperation}}"
    }
   ]
  },
  {
   "title": "Работа с документами",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keyoperation) (onec_apdex_total_value{profile=\"Работа с документами\", exported_instance=\"$instance\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Ключевые операции",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(keyoperation) (onec_apdex_value{profile=\"Работа с документами\", exported_instance=\"$instance\"}) < 0.85",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}